-- V10: Hotels module tables

CREATE TABLE hotels (
    id                   BIGINT        NOT NULL AUTO_INCREMENT,
    source               VARCHAR(50)   NOT NULL DEFAULT 'MANUAL',
    source_hotel_id      VARCHAR(200),
    name                 VARCHAR(300)  NOT NULL,
    city                 VARCHAR(100)  NOT NULL DEFAULT 'jaipur',
    area                 VARCHAR(200),
    address              VARCHAR(500),
    latitude             DECIMAL(10,7),
    longitude            DECIMAL(10,7),
    rating               DECIMAL(3,1),
    star_rating          INT,
    image_url            VARCHAR(1000),
    amenities_json       JSON,
    price_min            DECIMAL(10,2),
    price_max            DECIMAL(10,2),
    currency             VARCHAR(10)   NOT NULL DEFAULT 'INR',
    price_type           VARCHAR(20)   NOT NULL DEFAULT 'ESTIMATED',
    cheapest_vendor      VARCHAR(200),
    last_price_fetched_at DATETIME,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_hotels_source_id (source, source_hotel_id),
    INDEX idx_hotels_city     (city),
    INDEX idx_hotels_area     (area),
    INDEX idx_hotels_price_min(price_min),
    INDEX idx_hotels_rating   (rating),
    INDEX idx_hotels_price_type(price_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE hotel_price_cache (
    id              BIGINT        NOT NULL AUTO_INCREMENT,
    hotel_id        BIGINT        NOT NULL,
    check_in        DATE          NOT NULL,
    check_out       DATE          NOT NULL,
    adults          INT           NOT NULL DEFAULT 2,
    rooms           INT           NOT NULL DEFAULT 1,
    children        INT           NOT NULL DEFAULT 0,
    currency        VARCHAR(10)   NOT NULL DEFAULT 'INR',
    payload_json    LONGTEXT,
    min_price       DECIMAL(10,2),
    max_price       DECIMAL(10,2),
    cheapest_vendor VARCHAR(200),
    expires_at      DATETIME      NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_hpc_hotel_id  (hotel_id),
    INDEX idx_hpc_expires   (expires_at),
    INDEX idx_hpc_checkin   (check_in),
    INDEX idx_hpc_checkout  (check_out),
    CONSTRAINT fk_hpc_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
