CREATE TABLE places (
    id              BIGINT          NOT NULL AUTO_INCREMENT,
    slug            VARCHAR(200)    NOT NULL,
    name            VARCHAR(200)    NOT NULL,
    category        VARCHAR(100)    NOT NULL,
    area            VARCHAR(200),
    tagline         VARCHAR(500),
    short_desc      TEXT,
    overview        TEXT,
    entry_fee       DECIMAL(10,2)   NOT NULL DEFAULT 0,
    estimated_spend DECIMAL(10,2)   NOT NULL DEFAULT 0,
    duration        VARCHAR(100),
    best_time       VARCHAR(200),
    open_hours      VARCHAR(200),
    rating          DECIMAL(3,1)    NOT NULL DEFAULT 0,
    review_count    INT             NOT NULL DEFAULT 0,
    must_see        BOOLEAN         NOT NULL DEFAULT FALSE,
    image           VARCHAR(1000),
    tip             TEXT,
    nearby_json     JSON,
    nearby_food_json JSON,
    best_weather_json JSON,
    best_time_of_day_json JSON,
    latitude        DECIMAL(10,7),
    longitude       DECIMAL(10,7),
    city            VARCHAR(100)    NOT NULL DEFAULT 'jaipur',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_places_slug (slug),
    INDEX idx_places_name (name),
    INDEX idx_places_category (category),
    INDEX idx_places_area (area),
    INDEX idx_places_city (city),
    INDEX idx_places_must_see (must_see),
    INDEX idx_places_rating (rating)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE place_tags (
    id       BIGINT       NOT NULL AUTO_INCREMENT,
    place_id BIGINT       NOT NULL,
    tag      VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_place_tags_tag (tag),
    INDEX idx_place_tags_place (place_id),
    CONSTRAINT fk_place_tags_place FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
