-- Seed 15 places from frontend mockPlaces.js
INSERT INTO places (slug, name, category, area, tagline, short_desc, overview, entry_fee, duration, best_time, open_hours, rating, review_count, must_see, image, tip, nearby_json, nearby_food_json, best_weather_json, best_time_of_day_json, city) VALUES
('amber-fort','Amber Fort','Heritage','Amer, 11 km from city','The crown jewel of Jaipur — a fort that stops time','16th-century Mughal-Rajput fort with gilded palaces, mirror halls, and sweeping valley views.','Amer Fort, perched on a rocky hillside 11 km from Jaipur, is Rajasthan''s most spectacular fortress. Built by Raja Man Singh I in 1592, it masterfully blends Mughal and Hindu architecture. The Sheesh Mahal (Mirror Palace) glitters with thousands of tiny mirrors. A UNESCO World Heritage Site — one of India''s top five historical monuments.',200,'2–3 hrs','7–9 AM (sunrise, no crowds)','8 AM – 5:30 PM',4.8,24800,TRUE,'/images/places/Amer-Fort-Jaipur.jpg','Book online at asi.payumoney.com to skip the 45-min queue. Elephant ride is ₹1,200 extra.','["Jaigarh Fort","Nahargarh Fort","Panna Meena Ka Kund"]','["Anokhi Cafe","Four Seasons (Amer)"]','["winter","spring"]','["morning"]','jaipur'),
('city-palace','City Palace','Heritage','Old City, Jaipur','Royal residence turned magnificent museum','Sprawling palace complex with seven courtyards, royal museums, and the famous twin silver urns.','The City Palace was established by Maharaja Sawai Jai Singh II in 1727. Part of the palace is still a royal residence. The complex blends Rajput, Mughal and European architecture across seven courtyards.',300,'1.5–2 hrs','9–11 AM','9:30 AM – 5 PM',4.7,18200,TRUE,'https://s7ap1.scene7.com/is/image/incredibleindia/city-palace-jaipur-rajasthan-1','Combined ticket with Jantar Mantar saves ₹100. Audio guide (₹150) is absolutely worth it.','["Jantar Mantar","Hawa Mahal","Govind Dev Ji Temple"]','["LMB Restaurant","Peacock Rooftop Restaurant"]','["winter","summer","rainy"]','["morning","afternoon"]','jaipur'),
('hawa-mahal','Hawa Mahal','Heritage','Old City, Jaipur','The iconic Palace of Winds — symbol of Jaipur','Five-storey pink sandstone palace with 953 latticed windows, built for the royal ladies to observe street life.','Hawa Mahal was built in 1799 by Maharaja Sawai Pratap Singh. Its unique five-storey pink sandstone façade with 953 small windows was designed to allow royal women to observe street festivals in purdah.',50,'45 min','Morning 7–9 AM for photos','9 AM – 4:30 PM',4.6,31000,TRUE,'https://obms-tourist.rajasthan.gov.in/uploads/Hawamahal_2_1_2dcc3f37c1.jpg','Best photo from the street opposite, especially at golden hour. Visit early to avoid crowds.','["City Palace","Jantar Mantar","Johari Bazaar"]','["Wind View Cafe","Lassi Shop (street)"]','["winter","summer","rainy"]','["morning"]','jaipur'),
('nahargarh-fort','Nahargarh Fort','Heritage','Aravalli Hills, Jaipur','Best sunset panorama over the Pink City','Hilltop fort with jaw-dropping city views, a quirky wax museum, and a legendary rooftop cafe.','Nahargarh Fort was built by Maharaja Sawai Jai Singh II in 1734 as a retreat and defense post. It offers the most spectacular panoramic views of Jaipur, especially at sunset.',50,'1.5–2 hrs','4–7 PM (sunset)','10 AM – 5:30 PM',4.5,14600,FALSE,'https://www.travel-rajasthan.com/images/experiance-in-rajsthan/forts-and-palaces/nahargarh-fort-jaipur-travel-rajasthan.jpg','Take a cab up — the road is steep and narrow. Carry water. Sunset here is unforgettable.','["Amber Fort","Jaigarh Fort"]','["Padao Restaurant","Cafe Nahargarh"]','["rainy","winter"]','["evening"]','jaipur'),
('panna-meena-kund','Panna Meena Ka Kund','Hidden Gems','Amer (5 min from Amber Fort)','A hidden geometric masterpiece — free & uncrowded','Hauntingly beautiful 16th-century stepwell with criss-cross staircase geometry. A photographer''s dream.','Built in the 16th century, Panna Meena Ka Kund is one of the most photogenic and least-visited gems near Jaipur. Free entry. 5-minute walk from Amber Fort.',0,'30–45 min','7–9 AM','Always open',4.7,4200,FALSE,'https://yometro.com/images/places/panna-meena-ka-kund.jpg','Free entry. Go early for the best light. Monkeys are curious — keep food in your bag.','["Amber Fort","Amer Village","Jaigarh Fort"]','["Anokhi Cafe"]','["winter","rainy"]','["morning"]','jaipur'),
('jantar-mantar','Jantar Mantar','Heritage','Old City, Jaipur','The world''s largest sundial — astronomy meets architecture','UNESCO World Heritage astronomical observatory with 19 giant instruments built in the 18th century.','Jantar Mantar was built by Maharaja Sawai Jai Singh II between 1724–1735. It contains 19 major astronomical instruments. The Samrat Yantra sundial stands 27m tall and measures time accurate to 2 seconds.',100,'1 hr','9 AM – 12 PM','9 AM – 4:30 PM',4.5,9800,TRUE,'https://rajasthancab.b-cdn.net/uploads/blog/1744627377-blog-image.webp','Hire a local guide (₹300) — without context it looks like concrete ramps. With a guide, it''s mind-blowing.','["City Palace","Hawa Mahal"]','["Peacock Rooftop"]','["winter","summer"]','["morning"]','jaipur'),
('lassiwala','Lassiwala','Food','MI Road, Jaipur','Jaipur''s most iconic food experience since 1945','Legendary clay-cup lassi shop that sells out daily by 1 PM. Non-negotiable Jaipur ritual.','Lassiwala on MI Road has been serving Jaipur''s most iconic lassi since 1945. No frills — just three types: sweet, salty, and mango.',0,'20 min','8–10 AM (sells out by 1 PM)','8 AM – 1 PM (or sold out)',4.8,8900,TRUE,'https://b.zmtcdn.com/data/pictures/1/19464241/1cd12ee09bf5b308b16d273e47983795.jpg','Arrive before 10 AM. Sweet lassi ₹60, small ₹40. Smash your clay cup when done — that''s tradition.','["Albert Hall","Raj Mandir Cinema"]','[]','["summer","winter","rainy"]','["morning"]','jaipur'),
('anokhi-cafe','Anokhi Cafe','Cafes','Tilak Nagar, Jaipur','The best coffee in Jaipur inside a heritage haveli','Organic cafe in the Anokhi Museum of Hand Printing. Serene courtyard, great coffee, excellent salads.','Anokhi Cafe is a hidden gem inside the Anokhi Museum of Hand Printing. Serves healthy organic food — great salads, wraps, and exceptional filter coffee.',0,'45 min – 1 hr','11 AM – 3 PM','10:30 AM – 7 PM (closed Sun)',4.6,3100,FALSE,'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/e7/6d/bc/the-display-counter-to.jpg','The roasted beetroot salad and cold coffee are must-orders. Cash preferred.','["Amber Fort","Central Park"]','[]','["winter","summer","rainy"]','["morning","afternoon"]','jaipur'),
('johari-bazaar','Johari Bazaar','Shopping','Old City, Jaipur','Jaipur''s glittering jewellery street since centuries','The heart of Jaipur''s famous gem and jewellery trade — Kundan, Meenakari, precious stones at every turn.','Johari Bazaar (Jewellers'' Market) is where Jaipur''s legendary gem-cutting heritage comes alive. The city is one of the world''s top gem-cutting centres.',0,'1–2 hrs','6–9 PM','10 AM – 9 PM',4.4,7200,FALSE,'https://www.rajasthantourplanner.com/blog/wp-content/uploads/2024/09/Johari-Bazaar-Jaipur.jpg','Bargain at 60% of asking price. For expensive gems, get a hotel recommendation for a trusted shop.','["Hawa Mahal","Bapu Bazaar"]','["Handi Restaurant"]','["winter","summer"]','["evening"]','jaipur'),
('tapri-central','Tapri Central','Cafes','Near Nahargarh Road','Jaipur''s most beloved rooftop chai experience','Rooftop cafe serving 30+ chai varieties with views of the ancient city walls. Fairy-lit evenings.','Tapri Central is Jaipur''s most beloved chai café, set on a rooftop near Nahargarh Fort road. It serves over 30 chai varieties and snacks.',0,'45 min','4–8 PM','9 AM – 11 PM',4.5,5600,FALSE,'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/20/2c/41/14/the-outer-area-of-tapri.jpg','Masala chai and adrak chai are the best. Go at sunset for golden views over the city walls.','["Nahargarh Fort","Jaigarh Fort"]','[]','["winter","rainy"]','["evening","morning"]','jaipur'),
('bapu-bazaar','Bapu Bazaar','Shopping','Old City, Jaipur','The best market for textiles, jutis & Rajasthani crafts','Jaipur''s most popular shopping street for block-print fabrics, bangles, jutis, and handicraft souvenirs.','Bapu Bazaar runs parallel to MI Road and is lined with shops selling block-print fabrics, Rajasthani jutis, bangles, blue pottery, and leather goods.',0,'1–2 hrs','10 AM – 7 PM','10 AM – 8:30 PM',4.3,8700,FALSE,'https://jaipurtourism.co.in/images//tourist-places/bapu-bazar-jaipur/bapu-bazar-jaipur-india-tourism-photo-gallery.jpg','Bargain confidently. For block-print fabric, try Nehru Bazaar Street behind — better quality.','["Johari Bazaar","Hawa Mahal"]','["MI Road cafes"]','["winter","summer"]','["afternoon","evening"]','jaipur'),
('albert-hall','Albert Hall Museum','Heritage','Ram Niwas Garden','Rajasthan''s oldest museum in a stunning Indo-Saracenic building','Opened in 1887 — Rajasthani art, sculptures, miniature paintings, carpets, and an Egyptian mummy.','Albert Hall Museum is Rajasthan''s oldest museum, opened in 1887. The stunning Indo-Saracenic building was designed by Sir Samuel Swinton Jacob. Fully air-conditioned.',150,'1.5 hrs','10 AM – 12 PM','9 AM – 5 PM (Tue–Sun)',4.4,11500,FALSE,'https://s7ap1.scene7.com/is/image/incredibleindia/albert-hall-museum-jaipur-rajasthan-3-attr-hero','The building''s night illumination (7–10 PM) is spectacular. Visit before or after.','["Jantar Mantar","Hawa Mahal"]','["Garden cafe nearby"]','["summer","rainy","winter"]','["morning","afternoon","evening"]','jaipur'),
('bar-palladio','Bar Palladio','Bars','Narain Niwas Palace, Jaipur','An Italian blue paradise in the heart of Rajasthan','A stunning, vibrant blue bar inspired by Italian elegance and Mughal aesthetics.','Bar Palladio is a visual masterpiece located in the Narain Niwas Palace Hotel. Known for its brilliant blue interiors, floral motifs, and romantic tented gardens.',0,'2–3 hrs','6–9 PM','4 PM – 12 AM',4.6,6500,TRUE,'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/e3/37/10/bar-palladio-jaipur.jpg','Reserve well in advance, especially for weekend evenings. Dress code is smart casual.','["Albert Hall","Central Park"]','["Shikaar Bagh"]','["winter","summer","rainy"]','["evening","night"]','jaipur'),
('shikaar-bagh','Shikaar Bagh','Bars','Narain Niwas Palace, Jaipur','Rustic hunting-lodge style tavern','A cozy, vintage bar with wooden interiors, outdoor seating, and excellent multi-cuisine food.','Located right next to Bar Palladio, Shikaar Bagh offers a completely different vibe — resembling a colonial-era hunting lodge.',0,'2–3 hrs','7–10 PM','1 PM – 1 AM',4.5,4200,FALSE,'https://b.zmtcdn.com/data/pictures/2/18659102/47bc7948a47ff7bf05b6fae968601662.jpg','Try their wood-fired pizzas and cocktails. Great place for a relaxed evening.','["Bar Palladio","Albert Hall"]','["Bar Palladio"]','["winter","spring"]','["evening","night"]','jaipur'),
('townsend','Townsend - Art & Cask','Bars','Malaram Nagar, Jaipur','Premium restro-bar with live music','A lively, upscale spot known for its energetic vibe, great music, and global cuisine.','Townsend is one of Jaipur''s premier nightlife destinations. It boasts a massive indoor space and an airy outdoor patio.',0,'2–4 hrs','8 PM – 12 AM','1 PM – 1 AM',4.4,3800,FALSE,'https://b.zmtcdn.com/data/pictures/7/19665897/ab9c7e099a4c8a2990d5f2a1ecf57e8d.jpg','Book ahead on weekends. Great place to catch live performances.','["C-Scheme"]','[]','["winter","summer","rainy"]','["evening","night"]','jaipur');

-- Seed place tags
INSERT INTO place_tags (place_id, tag) SELECT id, 'Heritage' FROM places WHERE slug='amber-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Photography' FROM places WHERE slug='amber-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'UNESCO' FROM places WHERE slug='amber-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Must-see' FROM places WHERE slug='amber-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Heritage' FROM places WHERE slug='city-palace';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Museum' FROM places WHERE slug='city-palace';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Royal' FROM places WHERE slug='city-palace';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Architecture' FROM places WHERE slug='city-palace';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Heritage' FROM places WHERE slug='hawa-mahal';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Photography' FROM places WHERE slug='hawa-mahal';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Architecture' FROM places WHERE slug='hawa-mahal';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Iconic' FROM places WHERE slug='hawa-mahal';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Heritage' FROM places WHERE slug='nahargarh-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Sunset' FROM places WHERE slug='nahargarh-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Views' FROM places WHERE slug='nahargarh-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Photography' FROM places WHERE slug='nahargarh-fort';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Hidden Gems' FROM places WHERE slug='panna-meena-kund';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Photography' FROM places WHERE slug='panna-meena-kund';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Architecture' FROM places WHERE slug='panna-meena-kund';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Free' FROM places WHERE slug='panna-meena-kund';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Heritage' FROM places WHERE slug='jantar-mantar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'UNESCO' FROM places WHERE slug='jantar-mantar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Science' FROM places WHERE slug='jantar-mantar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Architecture' FROM places WHERE slug='jantar-mantar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Food' FROM places WHERE slug='lassiwala';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Iconic' FROM places WHERE slug='lassiwala';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Breakfast' FROM places WHERE slug='lassiwala';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Must-try' FROM places WHERE slug='lassiwala';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Cafes' FROM places WHERE slug='anokhi-cafe';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Organic' FROM places WHERE slug='anokhi-cafe';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Heritage' FROM places WHERE slug='anokhi-cafe';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Breakfast' FROM places WHERE slug='anokhi-cafe';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Shopping' FROM places WHERE slug='johari-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Jewellery' FROM places WHERE slug='johari-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Textiles' FROM places WHERE slug='johari-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Evening' FROM places WHERE slug='johari-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Cafes' FROM places WHERE slug='tapri-central';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Chai' FROM places WHERE slug='tapri-central';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Rooftop' FROM places WHERE slug='tapri-central';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Views' FROM places WHERE slug='tapri-central';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Evening' FROM places WHERE slug='tapri-central';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Shopping' FROM places WHERE slug='bapu-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Textiles' FROM places WHERE slug='bapu-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Handicrafts' FROM places WHERE slug='bapu-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Gifts' FROM places WHERE slug='bapu-bazaar';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Heritage' FROM places WHERE slug='albert-hall';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Museum' FROM places WHERE slug='albert-hall';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Architecture' FROM places WHERE slug='albert-hall';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Air-conditioned' FROM places WHERE slug='albert-hall';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Bars' FROM places WHERE slug='bar-palladio';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Nightlife' FROM places WHERE slug='bar-palladio';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Romantic' FROM places WHERE slug='bar-palladio';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Italian' FROM places WHERE slug='bar-palladio';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Bars' FROM places WHERE slug='shikaar-bagh';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Nightlife' FROM places WHERE slug='shikaar-bagh';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Vintage' FROM places WHERE slug='shikaar-bagh';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Outdoor' FROM places WHERE slug='shikaar-bagh';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Bars' FROM places WHERE slug='townsend';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Nightlife' FROM places WHERE slug='townsend';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Party' FROM places WHERE slug='townsend';
INSERT INTO place_tags (place_id, tag) SELECT id, 'Live Music' FROM places WHERE slug='townsend';
